### ISSUE TITLE
Lock world during Query iteration

### ISSUE THREAD

**Issue by mlange-42** [mlange-42/arche#12]
Arche does not (and will not) support adding or removing components od entire entities during query iteration. However, nothing prevents the user from trying it, with undefined behaviour.

As a first measure, lock the world when a query is created, and hand it back to unlock.

Later, add/remove operations could be buffered and executed at unlock.

**Comment by pxul** [comment]
Hi, first of all thanks for the great software. You mention in this issue that you may look to implement the ability to buffer component add/remove operations which would subsequently be executed after world unlock. I was wondering whether you had made any progress on planning to add this, or if not, what strategy you would recommend to achieve this behaviour in the meantime? Thanks!

**Comment by mlange-42** [comment]
Thanks @pxul for your interest!

Yeah, at the moment operations deferred by the engine are not planned. And yes, just do it as in the example. For performance, reuse the slice (as in the example) instead of creating a new one on every iteration.
