### ISSUE TITLE
Transitive relationships?

### ISSUE THREAD

**Issue by delaneyj** [mlange-42/arche#310]
Flecs has very robust relationships.  https://www.flecs.dev/flecs/md_docs_Relationships.html

One feature is a relationship can be transitive to 
A IsA B IsA C  IsA D therefore, A IsA D,  Is that possible in arche?

**Comment by mlange-42** [comment]
Hi @delaneyj,
Arche has relationships too, but by far not as comprehensive as Flecs does.
E.g., Arche supports only one relationship per entity (as the left part of the relation).

So, it is possible to construct a chain like in your example. However, there is no mechanism to automatically resolve the chain to "A IsA D". Not sure if Flecs has this ability.

Also, unlike Flecs, queries in Arche can only take into account one "level" of relationships. So you can query for `every entity that IsA <anything>` or `every entity that isA D`, but not `every entity that IsA <entity that HasA <...>>`.

I would definitely like to extend Arche's relationship features, but it is not easy without sacrificing performance in other areas (see also #254).

**Comment by mlange-42** [comment]
As long as there is no more comprehensive support for entity relations (see #254), this feature is out of scope for Arche. Entity relations will probably not be extended substantally in the near future, so closing this issue.
