### ISSUE TITLE
World state save/load

### ISSUE THREAD

**Issue by pxul** [mlange-42/arche#314]
Hi @mlange-42, hope you are well.

I'm looking to be able to save/export the state of a World to storage, and then to be able to load/import it at a later time. Is this something you've ever found the need to be able to do?

I've had a look through the current and past issues, and examples and can't see anything that suggests this is something that has been suggested previously, or that Arche currently supports.

Is it something that you think would be straightforward to implement? Is it something you would be interested in adding to the package? If not, would you have any suggestions or a direction to point me in as to how I might achieve this?

Thanks very much,
Paul

**Comment by mlange-42** [comment]
Hi Paul!
thank you for your interest and for suggesting this feature.

IMO it is definitely worth thinking about. However, if possible, I would prefer to provide it as a separate module, like the other [Tools](https://github.com/mlange-42/arche#tools). If some basic functionality in the core module is required for that, I have no problem adding it.

If you only use plain values in your components and do not use entity relations (neither the Arche feature, nor by storing entities anywhere in components), it should already almost work. Below is some code I experimented with to test that it is possible to serialize and deserialize components of unknown types (known only via reflection).

For things like entity relations, it becomes more complicated. It would either require to serialize most of the world state, incl. the exact IDs of entities, or to use some mapping to find referenced/related entities during deserialization.

I will probably set up a more comprehensive example and implement the missing functionality pointed out in the code below.

```go
package main

import (
	"encoding/json"
	"fmt"
	"reflect"

	"github.com/mlange-42/arche/ecs"
)

// CompA is an example component type
type CompA struct {
	IntValue  int  `json:"intValue"`
	BoolValue bool `json:"boolValue"`
}

func main() {
	world := ecs.NewWorld()
	compAId := ecs.ComponentID[CompA](&world)

	// Create an entity for testing.
	e1 := world.NewEntityWith(ecs.Component{
		ID:   compAId,
		Comp: &CompA{IntValue: 100, BoolValue: true},
	})

	// Just an example for a single component. There are world.Mask(entity) and query.Mask(entity) to get all component IDs for an entity.
	// Potentially, world.ComponentIds(entity) and query.ComponentIds(entity) could be added.
	component := world.Get(e1, compAId)

	// Arche will need to expose GetType(compId), as component types will be unknown.
	tp := reflect.TypeOf((*CompA)(nil)).Elem()

	// Encode to JSON, without knowing the type
	value := reflect.NewAt(tp, component).Interface()
	fmt.Printf("original comp: %s %v\n", reflect.TypeOf(value), value)

	jsonData, err := json.Marshal(value)
	if err != nil {
		fmt.Printf("could not marshal json: %s\n", err)
		return
	}
	fmt.Printf("json data: %s\n", jsonData)

	// Decode the JSON, without knowing the type
	newValue := reflect.New(tp).Interface()

	if err = json.Unmarshal(jsonData, &newValue); err != nil {
		fmt.Printf("could not unmarshal json: %s\n", err)
		return
	}

	fmt.Printf("decoded: %s %v\n", reflect.TypeOf(newValue), newValue)

	// Add the component of unknown type to a new entity
	e2 := world.NewEntityWith(ecs.Component{ID: compAId, Comp: newValue})

	// Get and check the just added component
	compA := (*CompA)(world.Get(e2, compAId))
	fmt.Printf("added component: %v\n", compA)
}
```

**Comment by mlange-42** [comment]
@pxul See here for a first simple implementation of a serialization module for Arche: https://github.com/mlange-42/arche-serde

**Comment by pxul** [comment]
Hi @mlange-42! Wow, that was a quick turnaround. Thanks very much for this, it looks great. I'll take it out for a spin and see how it goes. I am currently using relations, but removing them will be pretty straightforward. Thanks again, Paul.

**Comment by mlange-42** [comment]
👍 Already thinking about the relations / entity stuff...

**Comment by mlange-42** [comment]
@pxul Looks like I solved it. See mlange-42/arche-serde#3

To use it (as long as the branch is not merged), use

```
go get github.com/mlange-42/arche-serde@serialize-relations
```

Is should work with the `Relation` feature as well as with plain stored entities (no pointers to entities!!!).

**Comment by mlange-42** [comment]
@pxul You can now use the `main` branch of [github.com/mlange-42/arche-serde](https://github.com/mlange-42/arche-serde).

But it definitely requires some more in-depth testing.

**Comment by pxul** [comment]
Hi @mlange-42 - this is great, thanks so much for the fast work. I was out tonight but was reminded to send you a message of thanks (see attachment). I hope to take a look at this and start using it in the next couple of days.

Cheers,
Paul

![IMG_7525](https://github.com/mlange-42/arche/assets/31599723/c9da2336-a500-4c4d-971d-217f459380a3)

**Comment by mlange-42** [comment]
Closing this issue. Feel free to re-open or open a new one in case of any problems or questions.
