### ISSUE TITLE
Inconsistent types used for returned filters

### ISSUE THREAD

**Issue by TLINDEN** [mlange-42/arche#369]
I want to preallocate the filters and put them into a generic struct member. This works as long as I don't add `.Without()` or something similar to the filter:

```go
package main

import (
	"math/rand"

	"github.com/mlange-42/arche/ecs"
	"github.com/mlange-42/arche/filter"
	"github.com/mlange-42/arche/generic"
)

type Position struct {
	X float64
	Y float64
}

type Velocity struct {
	X float64
	Y float64
}

type Transparent struct {
	DoDamage bool
}

func main() {
	world := ecs.NewWorld()

	monsters := generic.NewMap2[Position, Velocity](&world)
	ghosts := generic.NewMap3[Position, Velocity, Transparent](&world)

	for i := 0; i < 10; i++ {
		e := monsters.New()
		pos, vel := monsters.Get(e)
		pos.X = rand.Float64() * 100
		pos.Y = rand.Float64() * 100

		vel.X = rand.NormFloat64()
		vel.Y = rand.NormFloat64()
	}

	for i := 0; i < 10; i++ {
		e := ghosts.New()
		pos, vel, trans := ghosts.Get(e)
		pos.X = rand.Float64() * 100
		pos.Y = rand.Float64() * 100

		vel.X = rand.NormFloat64()
		vel.Y = rand.NormFloat64()

		trans.DoDamage = true
	}

	posid := ecs.ComponentID[Position](&world)
	veloid := ecs.ComponentID[Velocity](&world)
	transid := ecs.ComponentID[Transparent](&world)

	monsterselector := filter.All(posid, veloid)
	ghostselector := filter.All(posid, veloid).Without(transid)

	selectors := []ecs.Mask{}

	selectors = append(selectors, monsterselector)
	selectors = append(selectors, ghostselector)

	// do stuff...
}
```

Go crys:
```default
./main.go:64:32: cannot use ghostselector (variable of type ecs.MaskFilter) as ecs.Mask value in argument to append
```

So it would be good (for me at least  :grin:) if they would be of the same type or there were a way to encapsulate the `ecs.MaskFilter` into a `ecs.Mask` (or vice versa).

best,
Tom

**Comment by TLINDEN** [comment]
PS: I **could** do something like this to get the same types, but I'm unsure what `.Exclusive()` without args does exaclty:
```go
monsterselector := filter.All(posid, veloid).Exclusive()
ghostselector := filter.All(posid, veloid).Without(transid)

selectors := []ecs.MaskFilter{}

selectors = append(selectors, monsterselector)
selectors = append(selectors, ghostselector)
```

**Comment by mlange-42** [comment]
Try this:

```
selector := []ecs.Filter{}
```

`ecs.Filter` is the interface all filters implement, incl. `Mask`.

Regarding `Exclusive()`, it creates a filter that matches exactly the components of a `Mask`. So it excludes entities that have any further components. Contrary, a simple `Mask` is non-exclusive, i.e. components not in the mask are allowed.

**Comment by mlange-42** [comment]
Maybe a few more hints.

Although you create only 2x 10 entities and it is not really critical here, batch-creation would be more efficient:

```go
monsters := generic.NewMap2[Position, Velocity](&world)

query := monsters.NewBatchQ(10)
for query.Next() {
    pos, vel := query.Get()
    pos.X = rand.Float64() * 100
    pos.Y = rand.Float64() * 100

    vel.X = rand.NormFloat64()
    vel.Y = rand.NormFloat64()
}
```

Personally, I usually avoid mixing generic and ID-based API. In your example, the selector stuff could also look like this:

```go
monsterselector := generic.NewFilter2[Position, Velocity](&world)
ghostselector := generic.NewFilter2[Position, Velocity](&world).Without(generic.T[](Transparent))

selectors := []ecs.Filter{}

selectors = append(selectors, monsterselector.Filter(&world))
selectors = append(selectors, ghostselector.Filter(&world))
```

But of course, mixing generic and ID-based is totally fine, too.

**Comment by TLINDEN** [comment]
Many many thanks for your help and insights. Regarding the mixing of generic and id's: I didn't knew (or realize) that I mixed the two apis :) So, only using the generic one is much better.

However:
```go
monsterselector := generic.NewFilter2[Position, Velocity](&world)
```
doesn't work:
```default
too many arguments in call to generic.NewFilter2[Position, Velocity]
        have (*ecs.World)
        want ()
```

The [example](https://github.com/mlange-42/arche/blob/main/examples/generic/main.go#L56) also uses no world argument. 

How is `NewFilrerX()` able to work on world without a reference to it? It's not global internally, isnt't it?

**Comment by mlange-42** [comment]
> Ah, I see, it gets the ref to world via `filter.Query(world)`.

Yeah, exactly. Sorry, just typed in the example without testing or letting the IDE take a look at it.

For efficiency, the stuff that needs the `World`, which is getting IDs from the types, is done only at the first call of `FilterX.Query()` and cached for subsequent calls. Getting the actual query from the world, of course, needs to be done on each call.

Closing as solved.
