### ISSUE TITLE
Benchmark Rendering Question

### ISSUE THREAD

**Issue by dezren39** [mlange-42/arche#371]
Hey! This is super cool!

I very much appreciate the detail in this library.

I had a question with the benchmarks, in your tests are the others rendering entities in their engines?

(say, ebitengine for donburi)

In some ways, I'd guess it's kind of hard to disentangle their ecs performance characteristics from the underlying engines.

I don't know all these libraries well enough to know exactly how standalone they can be.

Thank you again.

**Comment by mlange-42** [comment]
Hi @dezren39,
thank you for your interest and for the appreciation!

No, there is no rendering in any of the benchmarks. It is just pure ECS functionality that is run there. Where an ECS implementation is related to a game engine, it is sufficiently separated to be used standalone.

So, yes, some of them are really that slow!

**Comment by dezren39** [comment]
Wow!! Thanks again. That's a huge difference.

**Comment by mlange-42** [comment]
Closing as answered.

**Comment by mlange-42** [comment]
@dezren39 FYI: to make the benchmarks more transparent, I linked their code in the README in #375.
