### ISSUE TITLE
Slowdown during redraw and count error

### ISSUE THREAD

**Issue by TLINDEN** [mlange-42/arche#407]
In the game I am currently developing, I am using a grid of tiles. When a new level starts, I draw the whole grid to a cache image and then use this cache image as background for all other subsequent draws (like player, obstacles etc) on top of it. 

Now I have one entity which I call the "transient entity". Such a transient can be traversed by the player and turns into a solid wall tile once the player left it. So this is kind of a onetime door or fall door, whatever.

The problem is, that I then need to redraw the grid, since I added a new solid tile to it. When the grid is redrawn in the middle of the level, it can be seen, the game literally halts for a couple of milliseconds. Look at this video:

https://www.daemon.de/idisk/tmp/openquell-2024-02-29_18.12.31.mp4

Once the player sphere completely traversed the transient entity, it stops for a short moment, then continues to move. I measured it, it stays in the redraw loop for 200-300 ms, which are a couple of ebiten ticks and therefore visible.

This is the code I'm using for the redraw:
```go
func (system *GridSystem) Draw(screen *ebiten.Image) {
	op := &ebiten.DrawImageOptions{}
	query := system.Selector.Query(system.World)

	if !system.UseCache || query.Count() != system.Count {
		//if !system.UseCache {
		slog.Debug("entity number changes", "old", system.Count, "current", query.Count())
		// map not cached or cacheable, write it to the cache
		draw.Draw(system.Cache, system.Background.Bounds(), system.Background, image.ZP, draw.Src)

		system.Count = query.Count()

		for query.Next() {
			sprite, pos, _ := query.Get()

			//slog.Debug("drawing sprite", "sprite", sprite, "point", pos.Point())
			draw.Draw(
				system.Cache,
				image.Rect(pos.X, pos.Y, pos.X+pos.Cellsize, pos.Y+pos.Cellsize),
				sprite.Image, image.ZP, draw.Over)
		}

		op.GeoM.Reset()
		screen.DrawImage(system.Cache, op)

		system.UseCache = true
	} else {
		// use the cached map
		op.GeoM.Reset()
		screen.DrawImage(system.Cache, op)
		query.Close()
	}
}
```

In fact, this code is slow from the very start when I started the project, which was the very reason I introduced the cache mechanism.

The other problem I'm having is, that I remove the transient and add a solid. However, according to arche, 2 new entities have been added. I am printing the number of entities, here on level start:
```default
2024-02-29T06:11.26 CET DEBUG: entity number changes /home/scip/dev/openquell/systems/grid_system.go: 55                                                                                        
    current: 44                                                                                                                                                                                 
    old: 0
```

And here during/after the transition process:
```default
2024-02-29T06:09.03 CET DEBUG: entity number changes /home/scip/dev/openquell/systems/grid_system.go: 55                                                                                        
    current: 46                                                                                                                                                                                 
    old: 44  
```

This is the code where I turn the transient into a solid. The `EntitiestoMakeSolid` slice contains a struct, one member is the entity itself. It will be added to the slice when the traversal is finished.

```go
	for _, convertible := range EntitiestoMakeSolid {
		slog.Debug("transient remove")
		// remove transient entity
		system.World.RemoveEntity(convertible.Entity)

		// replace with solid entity
		slog.Debug("transient add solid")
		entity := system.SolidMapper.New()
		pos, render, _, _ := system.SolidMapper.Get(entity)

		// set it up apropriately
		pos.Set(&convertible.Position)
		render.Image = assets.Assets[convertible.NewSprite]

		//  also  setup the  grid  tile  with  a  new solid,  so  that
		// collision detection works
		system.GridContainer.Grid.SetSolidTile(
			assets.NewTileBlock(convertible.NewSprite),
			convertible.Position.Point(),
		)
	}
```

This code is being executed only once during the level, since there's only 1 transient entity.

So, I don't worry much about the invalid entity count yet, as long as the count changes when I add or remove tiles. But the incredible slowdown is annoying, especially when one looks at the arche examples where thousands of entities are being redrawn every tick. This drives me nuts :(

**Comment by mlange-42** [comment]
For the slowdown, I have no idea and can't see any critical points in the code you show. So far, I have never had problems with drawing speed of Ebiten, neither in my demos (you mention it), nor in this new project I just started: https://github.com/mlange-42/tiny-world

So I think drawing a few hundreds or even thousands of sprites should not be a problem. You also don't have a hell lot of different sprites, so it should not matter whether they are single images or come from an atlas.

Did you profile the code to verify that the lag really comes from this particular piece of code? Is it still there if you comment out only the `draw.Draw(...)`?

Not sure how you store sprites. It is a copy in each component (bad!)? A pointer to the same instance (better)? Personally, I prefer to store sprites in a central place, and have only the sprite index in the component (best). But still, this can't explain 200ms for 40-some sprites.

Regarding the entity count, that's interesting. Could you please check if counting with a full iteration gives the same result as `Query.Count`? That would help to check if it is a bug in `Query`, or rather in your code.

**Comment by TLINDEN** [comment]
Ok, I added some stats:
```go
start := time.Now()
		
draw.Draw(system.Cache, system.Background.Bounds(), system.Background, image.ZP, draw.Src)
slog.Debug("background", "duration", time.Since(start))

system.Count = query.Count()

slog.Debug("counting", "duration", time.Since(start))

for query.Next() {
	sprite, pos, _ := query.Get()

	draw.Draw(
		system.Cache,
		image.Rect(pos.X, pos.Y, pos.X+pos.Cellsize, pos.Y+pos.Cellsize),
		sprite.Image, image.ZP, draw.Over)
}

slog.Debug("loop", "duration", time.Since(start))

op.GeoM.Reset()
screen.DrawImage(system.Cache, op)

system.UseCache = true
slog.Debug("draw to screen", "duration", time.Since(start))
os.Exit(0)
```

This is the output:
```default
2024-03-01T09:26.34 CET DEBUG: background /home/scip/dev/openquell/systems/grid_system.go: 59 
    duration: 195.831328ms
2024-03-01T09:26.34 CET DEBUG: counting /home/scip/dev/openquell/systems/grid_system.go: 63 
    duration: 195.901653ms
2024-03-01T09:26.34 CET DEBUG: loop /home/scip/dev/openquell/systems/grid_system.go: 77 
    duration: 262.979618ms
2024-03-01T09:26.34 CET DEBUG: draw to screen /home/scip/dev/openquell/systems/grid_system.go: 83 
    duration: 263.281901ms
```

So, the background image takes the most time, but even if I comment it out, it still takes too long.

As for the storage: currently I am reading the sprites into a `map[string]*ebiten.Image` from an `embed.FS` and then during tile creation I store a pointer to it. So, the `sprite.Image` is a pointer to `*ebiten.Image`.

**Comment by TLINDEN** [comment]
Holy Cow!

I realized that I seem to have used the wrong API. Instead of using `draw.Draw()` I switched to `ebiten.Image.DrawImage()`:

```go
start := time.Now()

cache := ebiten.NewImage(system.Width, system.Height)
cache.DrawImage(system.Background, op)
slog.Debug("background", "duration", time.Since(start))

system.Count = query.Count()

slog.Debug("counting", "duration", time.Since(start))

for query.Next() {
	sprite, pos, _ := query.Get()
    
	op.GeoM.Reset()
	op.GeoM.Translate(float64(pos.X), float64(pos.Y))
	cache.DrawImage(sprite.Image, op)
}

slog.Debug("loop", "duration", time.Since(start))

op.GeoM.Reset()
screen.DrawImage(cache, op)

system.UseCache = true
slog.Debug("draw to screen", "duration", time.Since(start))
os.Exit(0)
```

Now, look how fast this is:
```default
2024-03-01T09:37.32 CET DEBUG: background /home/scip/dev/openquell/systems/grid_system.go: 104 
    duration: 123.176µs
2024-03-01T09:37.32 CET DEBUG: counting /home/scip/dev/openquell/systems/grid_system.go: 108 
    duration: 175.289µs
2024-03-01T09:37.32 CET DEBUG: loop /home/scip/dev/openquell/systems/grid_system.go: 119 
    duration: 207.148µs
2024-03-01T09:37.32 CET DEBUG: draw to screen /home/scip/dev/openquell/systems/grid_system.go: 125 
    duration: 228.167µs
```

That's a whopping 228us in summary :)

Ok, now that this is out of the way, I'm trying to look after the entity count thing.

**Comment by TLINDEN** [comment]
> EDIT: Actually, I count 45 wall tiles in the video before the change, not 44. Could it be that one of them is different and not covered by the query, and then also changes in the same tick?

LOL, my fault as well!

I've been tricked by my own game. One of the wall tiles is actually no wall tile, it just camouflages as one. See: https://youtu.be/9elySvz23tM :)

That is - the count is correct.


So, thanks a lot, again!


best,
Tom

**Comment by mlange-42** [comment]
@TLINDEN Great that you could solve all these problemns with my few hints!

Also worth to know that `draw.Draw` should better be avoided. Did not experience problems there so far, but I only use it to draw `image.RGBA` onto `image.RGBA` (in my sprite preprocessing), which is probably faster than using it with `image.Image` interface (which `ebiten.Image` is).

Closing as solved.
