### ISSUE TITLE
fix example/base

### ISSUE THREAD

**Issue by baozaolaoba-top** [mlange-42/arche#418]
https://github.com/mlange-42/arche/blob/ef139e3fee2306fb5da240e1da493afa193e8789/_examples/base/main.go#L40C1-L41C47

```go
		pos := (*Position)(world.Get(entity, posID))
		vel := (*Velocity)(world.Get(entity, velID))
```

**Comment by mlange-42** [comment]
@baozaolaoba-top Many thanks for reporting!
